OduncKitapASPNETMVCWebSolution_UI/Controllers/PartialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OduncKitapASPNETMVCWebSolution_BLL.Managers;
using OduncKitapASPNETMVCWebSolution_UI.Controllers;

namespace OduncKitapASPNETMVCWebSolution_UI.Controllers
{
    public class PartialsController : Controller
    {
        //Global alan
        KitapManager myKitapManager = new KitapManager();
        //Tüm partial'ları tek bir yerden yönetmek amacıyla partialsController oluşturduk.
        public PartialViewResult MenuPartialResult()
        {
            int toplamKitapSayisi = myKitapManager.TumAktifKitaplariGetir().Count();
            TempData["ToplamKitapSayisi"] = toplamKitapSayisi;

            return PartialView("_PartialMenu");
        }
    }
}

OduncKitapASPNETMVCWebSolution_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OduncKitapASPNETMVCWebSolution_UI/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Paneli</title>
    <!-- Bootstrap core CSS -->

    <link href="~/webpanel/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/webpanel/css/simple-sidebar.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        @{ 
            Html.RenderAction("MenuPartialResult","Partials");
        }
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                @*yeni eklendi*@
                <a href="#" id="menu-toggle">
                    <span class="glyphicon glyphicon-menu-hamburger" style="font-size:20px;"></span>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @*iptal olacak*@
                    @*<ul class="navbar-nav ml-auto mt-2 mt-lg-0">*@
                    @*yeni eklendi*@
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">AnaSayfa <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Hesap Bilgileri
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Profil</a>

                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Çıkış Yap</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/webpanel/vendor/jquery/jquery.min.js"></script>
    <script src="~/webpanel/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

OduncKitapASPNETMVCWebSolution_UI/Views/Shared/_PartialMenu.cshtml
<div class="bg-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading"><h4><strong>Ödünç Kitap Sistemi</strong></h4> </div>
    <div class="list-group list-group-flush">
        <a href="/DashBoard/Index" class="list-group-item list-group-item-action bg-light"><strong>Dashboard</strong></a>
        <a href="/Tur/Index" class="list-group-item list-group-item-action bg-light"><strong>Tür İşlemleri</strong></a>
        <a href="/Yazar/Index" class="list-group-item list-group-item-action bg-light"><strong>Yazar İşlemleri</strong></a>
        <a href="/Kitap/Index" class="list-group-item list-group-item-action bg-light"><strong>Kitap İşlemleri <span class="badge badge-info right" style="background-color:indianred">@TempData["ToplamKitapSayisi"]</span></strong></a>
        <a href="/OduncIslem/Index" class="list-group-item list-group-item-action bg-light"><strong>Ödünç İşlemler</strong></a>
        <a href="/Uye/Index" class="list-group-item list-group-item-action bg-light"><strong>Üye İşlemleri</strong></a>
        <a href="/Personel/Index" class="list-group-item list-group-item-action bg-light"><strong>Personel İşlemleri</strong></a>
    </div>
</div>